name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vue
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: build
        run: npm install && npm run build
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./vue
  server:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./express
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: "10"

      - name: install node deps
        run: npm install --only=production

      - name: env file
        run: |
          touch .env
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env
          echo TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} >> .env
          echo TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} >> .env
          echo GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} >> .env
          echo GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          cat .env

      - name: gcp auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: gcloud cli install
        uses: "google-github-actions/setup-gcloud@v0"

      - name: prepare data dir
        run: mkdir ./data

      - name: build index
        run: npm run reindex

      - name: sync data
        run: gsutil -m cp gs://dev-tube-index/index-new.json ./data

      - name: deploy
        run: "gcloud functions deploy api --trigger-http --runtime nodejs16 --memory=1024MB --timeout=30s --project=dev-tube"
